import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ShowSideBar from "@/components/side-bar/ShowSideBar";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex">
            <ShowSideBar />
            <div className="bg-[color:#F4F7FE] w-[100vw] h-[100vh]">
              {children}
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
